NXT-2179: Only cancel workflow when executing
Unnecessary call otherwise. And a pseudo-fix for NPE in
knime-server-client testflows.

java.lang.NullPointerException: Cannot invoke "org.knime.core.node.workflow.WorkflowManager.disableSuccessorsForExecution(org.knime.core.node.workflow.NodeID, int)" because the return value of "org.knime.core.node.workflow.WorkflowManager.getParent()" is null
  	at org.knime.core.node.workflow.WorkflowManager.disableNodeForExecution(WorkflowManager.java:2596)
  	at org.knime.core.node.workflow.WorkflowManager.disableNodeForExecution(WorkflowManager.java:2534)
  	at org.knime.core.node.workflow.WorkflowManager.cancelExecution(WorkflowManager.java:5820)
  	at org.knime.gateway.api.util.CoreUtil.lambda$3(CoreUtil.java:361)
  	at org.knime.gateway.api.util.CoreUtil.performActionOnWorkflow(CoreUtil.java:400)
  	at org.knime.gateway.api.util.CoreUtil.cancel(CoreUtil.java:361)
  	at org.knime.gateway.api.util.CoreUtil.cancelAndCloseLoadedWorkflow(CoreUtil.java:331)
  	at org.knime.gateway.impl.project.WorkflowServiceProjects.lambda$2(WorkflowServiceProjects.java:111)
  	at org.knime.gateway.impl.project.ProjectManager.removeProject(ProjectManager.java:225)
  	at org.knime.gateway.impl.project.WorkflowServiceProjects.removeProject(WorkflowServiceProjects.java:109)
  	at org.knime.workflowservices.LocalWorkflowBackend.discard(LocalWorkflowBackend.java:566)
  	at org.knime.workflowservices.LocalWorkflowBackend.lambda$0(LocalWorkflowBackend.java:142)

NXT-2179 (Workflows already loaded via 'Call Workflow (Service)' aren't taken into account)